substitutions:
  # Customization
  device_name: smartplug-01
  device_id: "97"
  friendly_name: Washing Machine Plug
  area: Bathroom

packages:
  smartplug_generic: !include
    file: ../esphome-elements/device.smartplug-generic.yaml
    vars:
      # Device settings and overrides
      current_res: 0.00117
      voltage_div: 755
      max_power: 3450
      # Device pinout
      red_led: GPIO0
      blue_led: GPIO2
      cf1_pin: GPIO4
      cf_pin: GPIO5
      sel_pin: GPIO12
      button_pin: GPIO13
      relay_pin: GPIO15

sensor:
  - id: !extend current
    filters:
      - calibrate_linear:
        - 8.728 -> 8.198
        - 0.219 -> 0.186
        - 0.285 -> 0.298
        - 0.153 -> 0.130
      - lambda: if (x < 0) return 0; else return x;
  - id: !extend voltage
    filters:
      - calibrate_linear:
        - 0.0 -> 0.0
        - 228.8 -> 226.8
        - 234.4 -> 232.1
  - id: !extend power
    filters:
      - calibrate_linear:
        - 3835 -> 1864.88
        - 57 -> 26.85
        - 71 -> 34.24
        - 35 -> 17.08
      - lambda: if (x < 0) return 0; else return x;
