substitutions:
  # Customization
  device_name: smartplug-01
  device_id: "97"
  friendly_name: Washing Machine Plug
  area: Bathroom

packages:
  smartplug_generic: !include ./esphome-elements/device.smartplug-generic.yaml

# Calibration
sensor:
  - id: !extend power_meter
    current:
      filters:
        - calibrate_linear:
          - 8.728 -> 8.198
          - 0.219 -> 0.186
          - 0.285 -> 0.298
          - 0.153 -> 0.130
        - lambda: if (x < 0) return 0; else return x;
    voltage:
      filters:
        - calibrate_linear:
          -   0.0 ->   0.0
          - 228.8 -> 226.8
          - 234.4 -> 232.1
    power:
      filters:
        - calibrate_linear:
          - 3835 -> 1864.88
          -   57 ->   26.85
          -   71 ->   34.24
          -   35 ->   17.08
        - lambda: if (x < 0) return 0; else return x;
