substitutions:
  # Customization
  device_name: switch-sonoff-minir2-03
  device_id: "123"
  friendly_name: <UNDECIDED>
  area: <UNDECIDED>

packages:
  sonoff_minir2: !include
    file: ./esphome-elements/device.sonoff-minir2.yaml
