substitutions:
  # Customization
  device_name: esp-307e28
  device_id: "84"
  friendly_name: Bedroom Wall Switch
  area: Bedroom

packages:
  device: !include ./esphome-elements/device.sonoff-t1eu-2g.yaml

# Human-friendly naming
binary_sensor:
  - id: !extend touchpad_left
    name: Ceiling Light Toggle
  - id: !extend touchpad_right
    name: Customizable Toggle
    disabled_by_default: true

switch:
  - id: !extend relay_left
    name: Ceiling Light
  - id: !extend relay_right
    name: Customizable
    disabled_by_default: true
