substitutions:
  # Customization
  device_name: esp-307e78
  device_id: "81"
  friendly_name: Office Wall Switch
  area: Office

packages:
  smartplug_generic: !include
    file: ./esphome-elements/device.sonoff-t1eu-2g.yaml

# Human-friendly naming
binary_sensor:
  - id: !extend touchpad_left
    name: Ceiling Lights Toggle
  - id: !extend touchpad_right
    name: Customizable Toggle
    disabled_by_default: true

switch:
  - id: !extend relay_left
    name: Ceiling Lights
  - id: !extend relay_right
    name: Customizable
    disabled_by_default: true
