substitutions:
  # Customization
  device_name: switch-sonoff-t1eu-2g-05
  device_id: "85"
  friendly_name: Bathroom Outer Wall Switch
  area: Bathroom

packages:
  smartplug_generic: !include
    file: ../esphome-elements/device.sonoff-t1eu-2g.yaml
