substitutions:
  # Customization
  device_name: switch-sonoff-minir2-04
  device_id: "124"
  friendly_name: Cabinets
  area: Living Room

packages:
  sonoff_minir2: !include
    file: ./esphome-elements/device.sonoff-minir2.yaml
