substitutions:
  # Customization
  device_name: esp-307faa
  device_id: "88"
  friendly_name: Bathroom Drawer Switch
  area: Bathroom

packages:
  device: !include ./esphome-elements/device.sonoff-t1eu-2g.yaml

# Human-friendly naming
binary_sensor:
  - id: !extend touchpad_left
    name: Fan Toggle
  - id: !extend touchpad_right
    name: Customizable Toggle
    disabled_by_default: true

switch:
  - id: !extend relay_left
    name: Fan
  - id: !extend relay_right
    name: Customizable
    disabled_by_default: true
