substitutions:
  # Customization
  device_name: switch-sonoff-t1eu-2g-02
  device_id: "82"
  friendly_name: Hall Wall Switch
  area: Hall

packages:
  smartplug_generic: !include
    file: ./esphome-elements/device.sonoff-t1eu-2g.yaml
