substitutions:
  # Customization
  device_name: esp-3082cf
  device_id: "85"
  friendly_name: Hall Wall Switch
  area: Hall

packages:
  device: !include ./esphome-elements/device.sonoff-t1eu-2g.yaml

# Human-friendly naming
binary_sensor:
  - id: !extend touchpad_left
    name: Corridor Light Toggle
  - id: !extend touchpad_right
    name: Ceiling Lights Toggle

switch:
  - id: !extend relay_left
    name: Corridor Lights
  - id: !extend relay_right
    name: Ceiling Light
